#! /bin/bash

SCRIPT="set-prompts"

# controlla se si hanno i diritti di root, se no termina l'esecuzione
function check_root_rights() {
	if [ "$( id -u )" -ne 0 ]; then
		echo -e "\e[1m[$SCRIPT]\e[0m sono necessari i diritti di root per continuare"
		exit 1
	fi
}

# se non si hanno i diritti di root si termina.
check_root_rights

# file di configurazione della bash di user e root
BASH_USER_CONFIG_FILE=~/.bashrc
BASH_ROOT_CONFIG_FILE=/root/.bashrc

# definizione dei colori
GREEN="\[\e[1;32m\]"
WHITE="\[\e[1;37m\]"
RED="\[\e[1;31m\]"
DEFAULT="\[\e[0m\]" #colore di default del testo

# recupero in nome dell'utente dal path della sua home dir
USER_HOME=~
USER=${USER_HOME//*\/}

# memorizza la presenza o meno di GIT prompt
GIT=""

echo -e "\n# MODIFICO IL PROMPT" >> $BASH_USER_CONFIG_FILE
echo -e "\n# MODIFICO IL PROMPT" >> $BASH_ROOT_CONFIG_FILE

echo -ne "\e[1m[$SCRIPT]\e[0m GIT prompt: "
if [ -f "/etc/bash_completion.d/git-prompt" ]; then
	GIT=true
	echo -e "\e[1;32mdisponibile\e[0m"
else
	GIT=false
	echo -e "\e[1;31massente\e[0m"
fi

# se nel sistema e' installato GIT...
if [ "$GIT" = "true" ]; then
	# definisce un prompt che mostra anche il ramo di sviluppo
	USER_PROMPT="$GREEN\u: $WHITE\w$DEFAULT"'\$(__git_ps1 \" [%s]\")'"$GREEN\n>$DEFAULT "
	ROOT_PROMPT="$RED\u: $WHITE\w$DEFAULT"'\$(__git_ps1 \" [%s]\")'"$RED\n>$DEFAULT "

	# inserisce il codice per abilitare la variabile GIT_PS1_SHOWDIRTYSTATE:
	# la varibile GIT_PS1_SHOWDIRTYSTATE per dire al prompt di mostrare 
	# un asterisco o un altro carattere per indicare che lo stato del ramo di
	# lavoro è "dirty" (quacosa è stato odificato e non è stato ancora fatto
	# il commit.
	echo "GIT_PS1_SHOWDIRTYSTATE=true" >> $BASH_USER_CONFIG_FILE
	echo "GIT_PS1_SHOWDIRTYSTATE=true" >> $BASH_ROOT_CONFIG_FILE

	# inserisce il codice per far caricare il codice fornito da GIT
	echo "source /etc/bash_completion.d/git-prompt" >> $BASH_USER_CONFIG_FILE
	echo "source /etc/bash_completion.d/git-prompt" >> $BASH_ROOT_CONFIG_FILE
else
	# definizione dei nuovi prompt per l'user e per root senza informazioni GIT
	USER_PROMPT="$GREEN\u: $WHITE\w$GREEN\n>$DEFAULT "
	ROOT_PROMPT="$RED\u: $WHITE\w$RED\n>$DEFAULT "	
fi

# scrive il codice pre modificare i prompt
echo  "export PS1=\"$USER_PROMPT\"" >> $BASH_USER_CONFIG_FILE
echo -e "\e[1m[$SCRIPT]\e[0m nuovo prompt per l'utente \e[1;32m$USER\e[0m settato "
if [ "$GIT" = "true" ]; then
	echo "              ed esteso con informazioni GIT"
fi

echo  "export PS1=\"$ROOT_PROMPT\"" >> $BASH_ROOT_CONFIG_FILE
echo -e "\e[1m[$SCRIPT]\e[0m nuovo prompt per l'utente \e[1;31mroot\e[0m settato "
if [ "$GIT" = "true" ]; then
	echo "              ed esteso con informazioni GIT"
fi

exit 0
